import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Topbar from "@/app/topbar";

const pretendard = localFont({
    src: './fonts/PretendardVariable.woff2',
    variable: "--font-pretendard"
})

export const metadata: Metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pretendard.variable} antialiased`}
      >
      <Topbar/>
        {children}
      </body>
    </html>
  );
}
